Add camera
miso-memoReal/memorial-frontend pull request #11
Opened 2023-10-21 12:14 UTC by ryuichi3811

カメラ機能の実装

2023-10-21 12:53 UTC, na2na-p requested changes
@ryuichi3811 

横からすみません！

`pubspec.lock`どうやらflutterだと「コミットしない」が推奨とのことで削除してます。
see: https://dart.dev/guides/libraries/private-files

`git rm --cached pubspec.lock`でgitの管理からは削除の上1コミット積んでください！

@haminem FEの方針わからないけど常にmainからマージボタン(Update branchのアレ)出しておく？

2023-10-21 12:57 UTC, na2na-p reviewed
実装詳細は見ていません！

修正は任意で、1点だけご確認ください！

2023-10-21 12:57 UTC, na2na-p commented on android/app/build.gradle
> +        minSdkVersion 21
本アプリケーションの仕様として、サポートの下限をAndroid 10(API level 29)としています！

<img width="879" alt="image" src="https://github.com/miso-memoReal/memorial-frontend/assets/49822810/4658fca3-2575-4b21-9eae-16c1ca43b6fe">

2023-10-21 13:07 UTC, ryuichi3811 commented
@na2na-p 

ご指摘ありがとうございます！！

2023-10-21 13:48 UTC, na2na-p approved these changes
ビルド通ることと、成果物確認しました！

山本指摘箇所についてはLGTMです！
あとはFEチームのレビュー待ちかも

2023-10-23 04:17 UTC, Takizawariku approved these changes

2023-10-23 04:17 UTC, merged